apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: default
  annotations:
    gitlab-token-rotate/enabled: "true"
    gitlab-token-rotate/registry: docker-registry-domain:1234
    gitlab-token-rotate/gitlab-endpoint: https://gitlab/api/v4
    gitlab-token-rotate/login: test
    gitlab-token-rotate/token: glpat-xxxxxxxxxxxxxxxxxxxx
data:
  .dockerconfigjson: e30K