apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-token-rotate
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-token-rotate
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-token-rotate
subjects:
- kind: ServiceAccount
  name: gitlab-token-rotate
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gitlab-token-rotate
  apiGroup: rbac.authorization.k8s.io